version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "${PORT}:80"  # Changed to map to internal port 80
    environment:
      - PORT=80  # Changed to 80
      - ACTIVE_POOL=${ACTIVE_POOL}
    depends_on:
      - app_blue
      - app_green
    volumes:
      - nginx_logs:/var/log/nginx
    restart: unless-stopped

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
      - PORT=3000
    ports:
      - "${BLUE_PORT}:3000"
    restart: unless-stopped

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
      - PORT=3000
    ports:
      - "${GREEN_PORT}:3000"
    restart: unless-stopped

  alert_watcher:
    build: ./alert_watcher
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD}
      - WINDOW_SIZE=${WINDOW_SIZE}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC}
      - NGINX_TARGET=${NGINX_TARGET}
    volumes:
      - nginx_logs:/var/log/nginx
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  nginx_logs:
