version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"  # Public entrypoint
    environment:
      - PORT=8080
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
      - PORT=3000
    ports:
      - "8081:3000"  # Blue direct access on 8081
    restart: unless-stopped

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
      - PORT=3000
    ports:
      - "8082:3000"  # Green direct access on 8082
    restart: unless-stopped
